# Form implementation generated from reading ui file 'ui/auth.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalWidget.setGeometry(QtCore.QRect(110, 10, 160, 271))
        self.verticalWidget.setStyleSheet("font: 10pt \"Microsoft JhengHei UI\";\n"
"background-color: #F8F8FF;\n"
"color: #352f36;\n"
"\n"
"")
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setStyleSheet("font-weight: bold")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(parent=self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setStyleSheet("color: #352f36")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.login = QtWidgets.QLineEdit(parent=self.verticalWidget)
        self.login.setMinimumSize(QtCore.QSize(0, 25))
        self.login.setStyleSheet("color: black;\n"
"border: 0px;\n"
"padding: 1px;\n"
"background-color: rgb(238, 238, 238);\n"
"margin: 1px;\n"
"border-radius: 10px")
        self.login.setObjectName("login")
        self.verticalLayout.addWidget(self.login)
        self.label_3 = QtWidgets.QLabel(parent=self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.password = QtWidgets.QLineEdit(parent=self.verticalWidget)
        self.password.setMinimumSize(QtCore.QSize(0, 25))
        self.password.setStyleSheet("color: black;\n"
"border: 0px;\n"
"padding: 1px;\n"
"background-color: rgb(238, 238, 238);\n"
"margin: 1px;\n"
"border-radius: 10px")
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.enterBtn = QtWidgets.QPushButton(parent=self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enterBtn.sizePolicy().hasHeightForWidth())
        self.enterBtn.setSizePolicy(sizePolicy)
        self.enterBtn.setMaximumSize(QtCore.QSize(16777215, 25))
        self.enterBtn.setBaseSize(QtCore.QSize(0, 25))
        self.enterBtn.setStyleSheet("padding: 5px;\n"
"background-color: rgb(85, 170, 127);\n"
"border-radius: 12px;\n"
"color: black;")
        self.enterBtn.setObjectName("enterBtn")
        self.verticalLayout.addWidget(self.enterBtn)
        self.guestBtn = QtWidgets.QPushButton(parent=self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.guestBtn.sizePolicy().hasHeightForWidth())
        self.guestBtn.setSizePolicy(sizePolicy)
        self.guestBtn.setMinimumSize(QtCore.QSize(0, 10))
        self.guestBtn.setMaximumSize(QtCore.QSize(16777215, 25))
        self.guestBtn.setBaseSize(QtCore.QSize(0, 0))
        self.guestBtn.setStyleSheet("padding: 5px;\n"
"background-color: rgb(217, 217, 217);\n"
"border-radius: 12px;\n"
"color: black;\n"
"")
        self.guestBtn.setObjectName("guestBtn")
        self.verticalLayout.addWidget(self.guestBtn)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Авторизация"))
        self.label.setText(_translate("Dialog", "Логин"))
        self.label_3.setText(_translate("Dialog", "Пароль"))
        self.enterBtn.setText(_translate("Dialog", "Войти"))
        self.guestBtn.setText(_translate("Dialog", "Продолжить как гость"))
