# Form implementation generated from reading ui file 'ui/card.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(789, 231)
        Form.setStyleSheet("QLabel {\n"
"    border: 1px solid #e0e0e0;\n"
"    border-radius: 6px;\n"
"    padding: 4px 8px;\n"
"    background-color: #f9f9f9;\n"
"    color: black\n"
"}")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 771, 230))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.photo = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.photo.setMinimumSize(QtCore.QSize(50, 0))
        self.photo.setMaximumSize(QtCore.QSize(200, 200))
        self.photo.setStyleSheet("background-color: transparent;\n"
"border: 0px")
        self.photo.setObjectName("photo")
        self.horizontalLayout.addWidget(self.photo)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.category = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.category.setStyleSheet("")
        self.category.setObjectName("category")
        self.horizontalLayout_2.addWidget(self.category)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(10, 16777215))
        self.label_2.setStyleSheet("background-color: transparent;\n"
"color: white;\n"
"border: 0px")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.name = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.name.setObjectName("name")
        self.horizontalLayout_2.addWidget(self.name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.description = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.manufacturer = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.manufacturer.setObjectName("manufacturer")
        self.verticalLayout.addWidget(self.manufacturer)
        self.supplier = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.supplier.setObjectName("supplier")
        self.verticalLayout.addWidget(self.supplier)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.price = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.price.setObjectName("price")
        self.horizontalLayout_3.addWidget(self.price)
        self.priceWithDisc = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.priceWithDisc.setText("")
        self.priceWithDisc.setObjectName("priceWithDisc")
        self.horizontalLayout_3.addWidget(self.priceWithDisc)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.unit = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.unit.setObjectName("unit")
        self.verticalLayout.addWidget(self.unit)
        self.amount = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.amount.setObjectName("amount")
        self.verticalLayout.addWidget(self.amount)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.discount = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.discount.setMaximumSize(QtCore.QSize(100, 16777215))
        self.discount.setStyleSheet("border: 0px")
        self.discount.setObjectName("discount")
        self.horizontalLayout.addWidget(self.discount)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.photo.setText(_translate("Form", "Фото"))
        self.category.setText(_translate("Form", "Категория товара"))
        self.label_2.setText(_translate("Form", "|"))
        self.name.setText(_translate("Form", "Наименование товара"))
        self.description.setText(_translate("Form", "Описание товара:"))
        self.manufacturer.setText(_translate("Form", "Производитель:"))
        self.supplier.setText(_translate("Form", "Поставщик:"))
        self.price.setText(_translate("Form", "Цена:"))
        self.unit.setText(_translate("Form", "Единица измерения:"))
        self.amount.setText(_translate("Form", "Кол-во на складе: "))
        self.discount.setText(_translate("Form", "Скидка"))
