# Form implementation generated from reading ui file 'ui/orderEdit.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.formLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 144, 201, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.statusCombo = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.statusCombo.setObjectName("statusCombo")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.statusCombo)
        self.b = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.b.setObjectName("b")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.b)
        self.address = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.address.setObjectName("address")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.address)
        self.q = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.q.setObjectName("q")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.q)
        self.a = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.a.setObjectName("a")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.a)
        self.s = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.s.setObjectName("s")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.s)
        self.dateOrder = QtWidgets.QDateEdit(parent=self.formLayoutWidget)
        self.dateOrder.setObjectName("dateOrder")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateOrder)
        self.dateGive = QtWidgets.QDateEdit(parent=self.formLayoutWidget)
        self.dateGive.setObjectName("dateGive")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateGive)
        self.editBtn = QtWidgets.QPushButton(parent=Dialog)
        self.editBtn.setGeometry(QtCore.QRect(150, 270, 75, 23))
        self.editBtn.setObjectName("editBtn")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(90, 10, 201, 121))
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget_2 = QtWidgets.QWidget(parent=self.groupBox)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 201, 101))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.label_2)
        self.amountLay = QtWidgets.QVBoxLayout()
        self.amountLay.setObjectName("amountLay")
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.amountLay)
        self.articulLay = QtWidgets.QVBoxLayout()
        self.articulLay.setObjectName("articulLay")
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.articulLay)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.b.setText(_translate("Dialog", "Статус"))
        self.q.setText(_translate("Dialog", "Адрес"))
        self.a.setText(_translate("Dialog", "Дата заказа"))
        self.s.setText(_translate("Dialog", "Дата выдачи"))
        self.editBtn.setText(_translate("Dialog", "Изменить"))
        self.groupBox.setTitle(_translate("Dialog", "Товары"))
        self.label.setText(_translate("Dialog", "Артикул"))
        self.label_2.setText(_translate("Dialog", "Кол-во"))
